
install:
	make -C IMUSensorTest install INSTALL_DIR=$(INSTALL_DIR)
	make -C RangeSensorTest install INSTALL_DIR=$(INSTALL_DIR)
	make -C MotorTest install INSTALL_DIR=$(INSTALL_DIR)
	make -C Robot install INSTALL_DIR=$(INSTALL_DIR)

clean:
	make -C IMUSensorTest clean
	make -C RangeSensorTest clean
	make -C MotorTest clean
	make -C Robot clean
